language: python

python:
  - 2.7
  - 3.4
  - 3.6

env:
  - DJANGO=1.11; PYPUPPETDB=0.1.1
  - DJANGO=1.11; PYPUPPETDB=0.3.2
  - DJANGO=1.10; PYPUPPETDB=0.1.1
  - DJANGO=1.10; PYPUPPETDB=0.3.2

install:
  - pip install -q django==$DJANGO
  - pip install -q pypuppetdb==$PYPUPPETDB
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

after_success:
  - coverage report -m
  - coveralls

notifications:
  email: false

script: coverage run --rcfile=.coveragesrc `which py.test` -v --pep8
