language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

env:
  - DJANGO=1.6.4

install:
  - pip install -U Django==$DJANGO
  - pip install -Ur requirements-test.txt

script:
  - coverage run --rcfile=.coveragerc `which py.test` -v --pep8

after_success:
  - coverage report -m
  - coveralls